### ISSUE TITLE
BE: Mongo for project

### ISSUE THREAD

**Issue by rajivtitus** [hatchways/team-callback-cats#2]
\- Set up the MongoDB for the project. The goal for this ticket is that the authentication features included in the starting code will be functional by storing user information in the database.

Here are some resources on the technologies:
\- \*\*MongoDB\*\* - use Mongoose for Node.js

**Comment by damienaries** [comment]
Is this a different ticket that the one we closed? I missed this assignement

**Comment by damienaries** [comment]
@rajivtitus Circling back on this. Does the set up I pushed cover this issue as well? I'm not able to log in or register, but I see the user data in the mongo shell when signing up.

**Comment by rajivtitus** [comment]
> @rajivtitus Circling back on this. Does the set up I pushed cover this issue as well? I'm not able to log in or register, but I see the user data in the mongo shell when signing up.

Hey Damien! We've already completed this so we can close this issue :)
